// Schema definition based on Experiment Pydantic model
const experimentSchema = {
  title: "Experiment Information",
  description:
    "Enter information about the experiments performed on the samples",
  type: "object",
  properties: {
    items: {
      type: "array",
      title: "Experiments",
      description: "List of experiments",
      minItems: 1,
      items: {
        type: "object",
        required: [
          "title",
          "experiment_type",
          "sample_ref",
          "library_name",
          "library_strategy",
          "library_source",
          "library_selection",
          "library_layout",
          "platform_type",
          "instrument_model",
        ],
        properties: {
          title: {
            type: "string",
            title: "Title",
            description: "Experiment title",
          },
          experiment_type: {
            type: "string",
            title: "Experiment Type",
            description: "Type of experiment performed",
            enum: [
              "Genomic",
              "Proteomic",
              "AP-MS",
              "Mass Spectrometry",
              "Imaging",
              "Multi-omics",
              "Other",
            ],
          },
          sample_ref: {
            type: "string",
            title: "Sample Reference",
            description: "Reference to the sample used in this experiment",
          },
          library_name: {
            type: "string",
            title: "Library Name",
            description: "Name of the library prepared for sequencing",
          },
          library_strategy: {
            type: "string",
            title: "Library Strategy",
            description: "Sequencing technique used",
            enum: [
              "WGS",
              "WXS",
              "RNA-Seq",
              "ChIP-Seq",
              "ATAC-seq",
              "miRNA-Seq",
              "Bisulfite-Seq",
              "Hi-C",
              "Exome",
              "Amplicon",
              "Proteome",
              "Phosphoproteome",
              "Interactome",
              "Metabolome",
              "LC-MS/MS",
              "SWATH-MS",
              "DIA-MS",
              "AP-MS",
              "BioID",
              "Microscopy",
              "OTHER",
            ],
          },
          library_source: {
            type: "string",
            title: "Library Source",
            description: "Type of source material",
            enum: [
              "GENOMIC",
              "TRANSCRIPTOMIC",
              "METAGENOMIC",
              "METATRANSCRIPTOMIC",
              "SYNTHETIC",
              "VIRAL RNA",
              "PROTEIN",
              "PEPTIDE",
              "CELL LYSATE",
              "IMMUNOPRECIPITATE",
              "TISSUE",
              "CELLULAR FRACTION",
              "ORGANOID",
              "OTHER",
            ],
          },
          library_selection: {
            type: "string",
            title: "Library Selection",
            description: "Method used to select the material",
            enum: [
              "RANDOM",
              "PCR",
              "RANDOM PCR",
              "RT-PCR",
              "HMPR",
              "MF",
              "CF-H",
              "CF-M",
              "CF-T",
              "CF-S",
              "CF-D",
              "CAGE",
              "RACE",
              "size fractionation",
              "ChIP",
              "MNase",
              "DNase",
              "Hybrid Selection",
              "Oligo-dT",
              "Inverse rRNA",
              "Antibody Pulldown",
              "Affinity Purification",
              "Protein A/G",
              "Proximity Labeling",
              "HPLC",
              "GEL",
              "OTHER",
            ],
          },
          library_layout: {
            type: "string",
            title: "Library Layout",
            description: "Library layout type",
            enum: ["SINGLE", "PAIRED", "NOT APPLICABLE"],
            default: "SINGLE",
          },
          platform_type: {
            type: "string",
            title: "Platform Type",
            description: "Sequencing or analytical platform type",
            enum: [
              "ILLUMINA",
              "ION_TORRENT",
              "PACBIO_SMRT",
              "OXFORD_NANOPORE",
              "BGISEQ",
              "CAPILLARY",
              "HELICOS",
              "COMPLETE_GENOMICS",
              "THERMO_ORBITRAP",
              "THERMO_QE",
              "SCIEX_TRIPLE_TOF",
              "BRUKER_TIMSTOF",
              "AGILENT_QTOF",
              "WATERS_SYNAPT",
              "ZEISS_MICROSCOPE",
              "LEICA_MICROSCOPE",
              "NIKON_MICROSCOPE",
              "OLYMPUS_MICROSCOPE",
              "OTHER",
            ],
          },
          instrument_model: {
            type: "string",
            title: "Instrument Model",
            description: "Specific instrument model used",
          },
          treatment: {
            type: "object",
            title: "Treatment",
            description: "Treatment details (if applicable)",
            required: ["treatment_applied"],
            properties: {
              treatment_applied: {
                type: "boolean",
                title: "Treatment Applied",
                description:
                  "Indicates if a treatment was applied to the sample",
                default: false,
              },
              treatment_agent: {
                type: "string",
                title: "Treatment Agent",
                description: "Agent used for treatment (drug, compound, etc.)",
              },
              treatment_duration: {
                type: "string",
                title: "Treatment Duration",
                description: "Duration of treatment (e.g., '24h', '2 days')",
              },
              treatment_concentration: {
                type: "string",
                title: "Treatment Concentration",
                description: "Concentration of treatment agent (e.g., '10 µM')",
              },
              control_type: {
                type: "string",
                title: "Control Type",
                description: "Type of control used",
                enum: [
                  "Vehicle",
                  "Untreated",
                  "Negative Control",
                  "Positive Control",
                  "Isotype Control",
                  "Scrambled Control",
                  "Other",
                ],
              },
            },
          },
          ms_parameters: {
            type: "object",
            title: "Mass Spectrometry Parameters",
            description: "Parameters specific to mass spectrometry experiments",
            properties: {
              acquisition_mode: {
                type: "string",
                title: "Acquisition Mode",
                description: "MS acquisition mode",
                enum: [
                  "DDA",
                  "DIA",
                  "SRM/MRM",
                  "PRM",
                  "SWATH",
                  "TOP-DOWN",
                  "OTHER",
                ],
              },
              fragmentation_method: {
                type: "string",
                title: "Fragmentation Method",
                description: "Method used for ion fragmentation",
                enum: ["CID", "HCD", "ETD", "ECD", "UVPD", "OTHER"],
              },
              chromatography_type: {
                type: "string",
                title: "Chromatography Type",
                description: "Type of chromatography used",
                enum: ["RPLC", "HILIC", "SCX", "SEC", "IEX", "IMAC", "OTHER"],
              },
              mass_analyzer: {
                type: "string",
                title: "Mass Analyzer",
                description: "Type of mass analyzer used",
                enum: [
                  "Orbitrap",
                  "TOF",
                  "Quadrupole",
                  "Ion Trap",
                  "FT-ICR",
                  "OTHER",
                ],
              },
            },
          },
          imaging_parameters: {
            type: "object",
            title: "Imaging Parameters",
            description: "Parameters specific to imaging experiments",
            properties: {
              imaging_type: {
                type: "string",
                title: "Imaging Type",
                description: "Type of imaging performed",
                enum: [
                  "Brightfield",
                  "Fluorescence",
                  "Confocal",
                  "Super-resolution",
                  "Electron Microscopy",
                  "Light Sheet",
                  "Two-photon",
                  "OTHER",
                ],
              },
              staining_method: {
                type: "string",
                title: "Staining Method",
                description: "Method used for staining/labeling",
                enum: [
                  "Fluorescent Protein",
                  "Immunofluorescence",
                  "FISH",
                  "Chemical Dye",
                  "H&E",
                  "None",
                  "OTHER",
                ],
              },
              magnification: {
                type: "string",
                title: "Magnification",
                description: "Magnification used (e.g., '40x', '63x')",
              },
              resolution: {
                type: "string",
                title: "Resolution",
                description: "Spatial resolution of images",
              },
            },
          },
        },
      },
    },
  },
  // Define common fields that should be shared across all experiments
  commonFields: [
    "experiment_type",
    "sample_ref",
    "library_name",
    "library_strategy",
    "library_source",
    "library_selection",
    "library_layout",
    "platform_type",
    "instrument_model",
  ],
};

export default experimentSchema;
