// Schema definition based on Experiment Pydantic model
const experimentSchema = {
  title: "Experiment Information",
  description:
    "Enter information about the experiments performed on the samples",
  type: "object",
  properties: {
    items: {
      type: "array",
      title: "Experiments",
      description: "List of experiments",
      minItems: 1,
      items: {
        type: "object",
        required: [
          "accession",
          "title",
          "study_ref",
          "sample_ref",
          "library_name",
          "library_strategy",
          "library_source",
          "library_selection",
          "library_layout",
          "platform_type",
          "instrument_model",
        ],
        properties: {
          accession: {
            type: "string",
            title: "Accession",
            description: "Unique experiment identifier",
          },
          title: {
            type: "string",
            title: "Title",
            description: "Experiment title",
          },
          study_ref: {
            type: "string",
            title: "Study Reference",
            description: "Reference to the study this experiment belongs to",
          },
          sample_ref: {
            type: "string",
            title: "Sample Reference",
            description: "Reference to the sample used in this experiment",
          },
          library_name: {
            type: "string",
            title: "Library Name",
            description: "Name of the library prepared for sequencing",
          },
          library_strategy: {
            type: "string",
            title: "Library Strategy",
            description: "Sequencing technique used",
            enum: [
              "WGS",
              "WXS",
              "RNA-Seq",
              "ChIP-Seq",
              "ATAC-seq",
              "miRNA-Seq",
              "Bisulfite-Seq",
              "Hi-C",
              "Exome",
              "Amplicon",
              "OTHER",
            ],
          },
          library_source: {
            type: "string",
            title: "Library Source",
            description: "Type of source material",
            enum: [
              "GENOMIC",
              "TRANSCRIPTOMIC",
              "METAGENOMIC",
              "METATRANSCRIPTOMIC",
              "SYNTHETIC",
              "VIRAL RNA",
              "OTHER",
            ],
          },
          library_selection: {
            type: "string",
            title: "Library Selection",
            description: "Method used to select the material",
            enum: [
              "RANDOM",
              "PCR",
              "RANDOM PCR",
              "RT-PCR",
              "HMPR",
              "MF",
              "CF-H",
              "CF-M",
              "CF-T",
              "CF-S",
              "CF-D",
              "CAGE",
              "RACE",
              "size fractionation",
              "ChIP",
              "MNase",
              "DNase",
              "Hybrid Selection",
              "Oligo-dT",
              "Inverse rRNA",
              "OTHER",
            ],
          },
          library_layout: {
            type: "string",
            title: "Library Layout",
            description: "Library layout type",
            enum: ["SINGLE", "PAIRED"],
            default: "SINGLE",
          },
          nominal_length: {
            type: "string",
            title: "Nominal Length",
            description: "Average insert size (for paired-end)",
          },
          platform_type: {
            type: "string",
            title: "Platform Type",
            description: "Sequencing platform type",
            enum: [
              "ILLUMINA",
              "ION_TORRENT",
              "PACBIO_SMRT",
              "OXFORD_NANOPORE",
              "BGISEQ",
              "CAPILLARY",
              "HELICOS",
              "COMPLETE_GENOMICS",
              "OTHER",
            ],
          },
          instrument_model: {
            type: "string",
            title: "Instrument Model",
            description: "Specific sequencing instrument used",
          },
        },
      },
    },
  },
};

export default experimentSchema;
