export interface SubDoc {
    key: string;        // machine key (e.g., "findable")
    name: string;       // display (e.g., "Findable")
    definition: string;
    logic: string;      // "source_property_logic" or "Logic: ..." from your notes
    statusNotes: string;
    subId?: string;     // optional like "0.a"
  }
  
  type Docs = Record<
    | "fairness"
    | "provenance"
    | "characterization"
    | "pre_model_explainability"
    | "ethics"
    | "sustainability"
    | "computability",
    SubDoc[]
  >;
  
  export const AI_READY_DOCS: Docs = {
    fairness: [
      {
        key: "findable",
        name: "Findable",
        subId: "0.a",
        definition:
          "Deposit datasets in a searchable FAIR-compliant repository with globally unique persistent identifiers resolvable to richly descriptive, machine-readable metadata.",
        logic: "root['@id'], root['identifier'] (for DOI)",
        statusNotes:
          "Directly Mapped. Check for the presence of a resolvable ARK and/or DOI.",
      },
      {
        key: "accessible",
        name: "Accessible",
        subId: "0.b",
        definition:
          "Descriptive metadata should always be available even if data are restricted/unavailable; conform to standards like DCAT or schema.org.",
        logic:
          'Default Statement: "The RO-Crate\'s JSON-LD metadata is machine-readable and publicly accessible by design."',
        statusNotes:
          "Inferred. Accessibility in FAIR refers to the metadata, which is always public for an RO-Crate.",
      },
      {
        key: "interoperable",
        name: "Interoperable",
        subId: "0.c",
        definition:
          "Provide data and metadata using formally defined specifications where possible.",
        logic:
          'Default Statement: "The dataset uses the schema.org vocabulary within the RO-Crate framework and conforms to the Croissant RAI specification for interoperability."',
        statusNotes:
          "Inferred. Use of common, standard formats (RO-Crate, schema.org, Croissant) is the evidence.",
      },
      {
        key: "reusable",
        name: "Reusable",
        subId: "0.d",
        definition:
          "Attach a clear usage license or define a Data Use Agreement (DUA) with automated acknowledgment/tracking.",
        logic: "root['license']",
        statusNotes:
          "Directly Mapped. The license is the key indicator of reusability. Versioning also supports it.",
      },
    ],
    provenance: [
      {
        key: "transparent",
        name: "Transparent",
        subId: "1.a",
        definition:
          "Identify sources of data back to reasonable ground-truth (e.g., EHR, trials, lab data).",
        logic:
          "Count all top-level `Dataset` entities that are not generated by a `Computation` or `Experiment` within the crate.",
        statusNotes:
          "Inferred. Requires root-node detection in the internal provenance graph.",
      },
      {
        key: "traceable",
        name: "Traceable",
        subId: "1.b",
        definition:
          "Identify important data transformation steps with links to software using machine-readable representations (e.g., PROV-O/EVI).",
        logic:
          "Count all `Computation` and `Experiment` entities within the crate (e.g., '50 steps documented').",
        statusNotes:
          "Inferred. Traceability reflected by number of documented transformations.",
      },
      {
        key: "interpretable",
        name: "Interpretable",
        subId: "1.c",
        definition:
          "Make software for key transformation/analysis steps available in a sustainable repository.",
        logic:
          "Count unique `Software` entities linked from `Computation`/`Experiment` (e.g., '3 software instances documented').",
        statusNotes:
          "Inferred. Demonstrated by linking to the software used.",
      },
      {
        key: "key_actors_identified",
        name: "Key Actors identified",
        subId: "1.d",
        definition:
          "Identify people/organizations responsible for obtaining/processing data and involved samples/subjects.",
        logic: "root['author'], root['publisher'], root['principalInvestigator']",
        statusNotes:
          "Directly Mapped. These fields directly identify key parties.",
      },
    ],
    characterization: [
      {
        key: "semantics",
        name: "Semantics",
        subId: "2.a",
        definition:
          "Use full descriptive metadata (abstract, keywords, subject-specific vocabularies) to enable discovery.",
        logic:
          'Default Statement: "Data is semantically described using the schema.org vocabulary within a machine-readable RO-Crate."',
        statusNotes:
          "Inferred. RO-Crate structure provides semantic context.",
      },
      {
        key: "statistics",
        name: "Statistics",
        subId: "2.b",
        definition:
          "Provide appropriate statistical characterizations of key features where appropriate; encode missing values consistently.",
        logic:
          "Count `Dataset` entities with `hasSummaryStatistics`; report volume and availability.",
        statusNotes:
          "Inferred. High-level overview of volume and the presence of summary statistics.",
      },
      {
        key: "standards",
        name: "Standards",
        subId: "2.c",
        definition:
          "Provide a machine-readable data dictionary or schema for each dataset; reference applicable standards.",
        logic:
          'Default Statement: "This dataset adheres to RO-Crate 1.2 and Croissant RAI 1.0 community standards."',
        statusNotes: "Inferred. Adherence to standards is the evidence.",
      },
      {
        key: "potential_sources_of_bias",
        name: "Potential Sources of Bias",
        subId: "2.d",
        definition:
          "Describe known sources of bias, assumptions, missingness explanations, and representativeness (e.g., disease vs. control).",
        logic: "rai:dataBiases (from --potential-sources-of-bias)",
        statusNotes: "Directly Mapped. Pull the user-provided bias statement.",
      },
      {
        key: "data_quality",
        name: "Data Quality",
        subId: "2.e",
        definition:
          "Describe quality control procedures applied and link to their description.",
        logic: "N/A",
        statusNotes:
          "Gap/TODO. Requires a dedicated metadata field for a data quality statement.",
      },
    ],
    pre_model_explainability: [
      {
        key: "data_documentation_template",
        name: "Data Documentation Templates",
        subId: "3.a",
        definition:
          "Machine-readable/human-readable docs covering a domain-appropriate subset of Datasheets/Healthsheets.",
        logic:
          'Default Statement: "Documentation is provided via RO-Crate JSON-LD, HTML Datasheet, and Croissant RAI properties."',
        statusNotes:
          "Inferred. The set of documentation artifacts fulfills this.",
      },
      {
        key: "fit_for_purpose",
        name: "Fit for Purpose",
        subId: "3.b",
        definition:
          "Identify appropriate/inappropriate AI use cases; link to prior analyses using this data.",
        logic: "rai:dataUseCases, rai:dataLimitations",
        statusNotes:
          "Directly Mapped. Designed for this purpose.",
      },
      {
        key: "verifiable",
        name: "Verifiable",
        subId: "3.c",
        definition:
          "Provide integrity mechanisms (e.g., checksum) for raw/processed data.",
        logic:
          "Calculate % of `Dataset`/`Software` entities with an `md5` property.",
        statusNotes:
          "Inferred. Report % of files with verifiable checksums.",
      },
    ],
    ethics: [
      {
        key: "ethically_acquired",
        name: "Ethically Acquired",
        subId: "4.a",
        definition:
          "Describe ethical acquisition (e.g., Belmont principles) sufficient to evaluate intended use; include management plan.",
        logic: "rai:dataCollection, human-subject",
        statusNotes:
          "Directly Mapped (RAI). `dataCollection` narrative is primary evidence.",
      },
      {
        key: "ethically_managed",
        name: "Ethically Managed",
        subId: "4.b",
        definition:
          "Data processing, storage, access, and use align with ethical principles throughout lifecycle; indicate privacy protections.",
        logic:
          'root["additionalProperty"] where name is "Data Governance Committee", ethicalReview',
        statusNotes:
          "Inferred. Use governance committee + ethical review contact.",
      },
      {
        key: "ethically_disseminated",
        name: "Ethically Disseminated",
        subId: "4.c",
        definition:
          "Specify license/DUA (or contact for DUA); specify data access committee contact if needed.",
        logic:
          "root['license'], prohibited-uses, rai:personalSensitiveInformation",
        statusNotes:
          "Directly Mapped. License, prohibited uses, and sensitive info are direct evidence.",
      },
      {
        key: "secure",
        name: "Secure",
        subId: "4.d",
        definition:
          "Specify security requirements for storing and accessing the data.",
        logic: "root['confidentialityLevel']",
        statusNotes:
          "Directly Mapped. Indicates security posture.",
      },
    ],
    sustainability: [
      {
        key: "persistent",
        name: "Persistent",
        subId: "5.a",
        definition:
          "Ensure unprocessed data is preserved in an archive adhering to laws/retention guidelines to enable future reprocessing/publishing.",
        logic: "root['@id'], root['identifier'] (DOI)",
        statusNotes:
          "Directly Mapped. Use of persistent identifiers.",
      },
      {
        key: "domain_appropriate",
        name: "Domain-appropriate",
        subId: "5.b",
        definition:
          "Deposit in a FAIR, domain-appropriate repository if available; include maintenance plan.",
        logic: "maintenance-plan (rai:dataReleaseMaintenancePlan)",
        statusNotes:
          "Directly Mapped. Replaced original with a concrete maintenance-plan property.",
      },
      {
        key: "well_governed",
        name: "Well-governed",
        subId: "5.c",
        definition:
          "Select repository/governance that supports stewardship, policy changes, and fairness.",
        logic: 'root["additionalProperty"] where name is "Data Governance Committee"',
        statusNotes:
          "Inferred. Evidence of a named governance body.",
      },
      {
        key: "associated",
        name: "Associated",
        subId: "5.d",
        definition:
          "Document project-level connections between data components in a machine-readable way.",
        logic:
          'Default Statement: "All data, software, and computations are explicitly linked in the RO-Crate\'s provenance graph."',
        statusNotes:
          "Inferred. A well-formed RO-Crate associates components.",
      },
    ],
    computability: [
      {
        key: "standardized",
        name: "Standardized",
        subId: "6.a",
        definition:
          "Datasets follow documented standards and adherence can be validated deterministically.",
        logic:
          "List all unique `format` values from `Dataset` and `Software` entities.",
        statusNotes:
          "Inferred. Summarize standardized file formats in the crate.",
      },
      {
        key: "computationally_accessible",
        name: "Computational Accessibility",
        subId: "6.b",
        definition:
          "Provide programmatic access via established exchange protocols or well-documented API.",
        logic:
          'Default Statement: "Data is hosted in public repositories (e.g., NCBI, MassIVE, Dataverse) that support programmatic access."',
        statusNotes:
          "Inferred. Assumes repository with API (standard for FAIR data).",
      },
      {
        key: "portable",
        name: "Portable",
        subId: "6.c",
        definition:
          "Maximize portability across compute resources; document required resources machine-readably.",
        logic:
          'Default Statement: "Dataset is packaged as a self-contained RO-Crate for portability."',
        statusNotes:
          "Inferred. RO-Crate standard itself is evidence.",
      },
      {
        key: "contextualized",
        name: "Contextualized",
        subId: "6.d",
        definition:
          "Include considerations on splits/withheld info; provide examples that convey structure and content where possible.",
        logic:
          'Default Statement: "Context is provided by the RO-Crate graph and properties such as `rai:dataLimitations`."',
        statusNotes:
          "Inferred. Combination of graph structure and RAI fields provides context.",
      },
    ],
  };
  
  export function getSubDocsFor(
    criterionId: keyof typeof AI_READY_DOCS
  ): SubDoc[] {
    return AI_READY_DOCS[criterionId] ?? [];
  }
  