import {
  RawGraphEntity,
  EvidenceNodeData,
  EvidenceNode,
  EvidenceEdge,
} from "../types/graph";
import { GraphDataService } from "../hooks/GraphDataService";

const MAX_LABEL_LENGTH = 50;
const feUrl = window.location.origin + "/view/";

export function getEntityType(typeUri: string | string[] | undefined): string {
  if (!typeUri) return "Unknown";
  const typeString = Array.isArray(typeUri) ? typeUri[0] : typeUri;
  return typeString.split(/[#\/]/).pop() || "Unknown";
}

export function abbreviateName(
  name: string | undefined,
  maxLength = MAX_LABEL_LENGTH
): string {
  if (!name) return "";
  if (name.length <= maxLength) return name;
  return name.substring(0, maxLength - 3) + "...";
}

export function formatPropertyValue(value: any, propKey?: string): string {
  if (value === null || value === undefined) {
    return "<em>Not specified</em>";
  }

  if (typeof value === "string") {
    if (value.startsWith("ark:")) {
      const fullUrl = `${feUrl}${value}`;
      return `<a href="${fullUrl}" target="_blank" rel="noopener noreferrer">${value}</a>`;
    }

    const urlRegex = /^(https?:\/\/\S+)$/;
    if (urlRegex.test(value)) {
      return `<a href="${value}" target="_blank" rel="noopener noreferrer">${value}</a>`;
    }

    if (propKey === "command") {
      return `<pre>${value}</pre>`;
    }

    return String(value);
  }

  if (Array.isArray(value)) {
    return value.map((item) => formatPropertyValue(item)).join("<br/>");
  }

  if (typeof value === "object" && value !== null) {
    if (value["@id"]) {
      return formatPropertyValue(value["@id"]);
    }
    try {
      return `<pre>${JSON.stringify(value, null, 2)}</pre>`;
    } catch (e) {
      return "[Object]";
    }
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  return String(value);
}

export function getDisplayableProperties(
  entityData: RawGraphEntity | undefined
): Record<string, any> {
  const excludeKeys = [
    "@id",
    "@type",
    "generatedBy",
    "usedDataset",
    "usedSoftware",
    "usedSample",
    "usedInstrument",
    "name",
    "label",
    "description",
  ];

  const properties: Record<string, any> = {};
  if (!entityData) return properties;

  for (const key in entityData) {
    if (!excludeKeys.includes(key) && !key.startsWith("_")) {
      properties[key] = entityData[key];
    }
  }
  return properties;
}

export function createEvidenceNode(
  entityData: RawGraphEntity,
  visibleNodes: Set<string>,
  dataService: GraphDataService
): EvidenceNode {
  const id = entityData["@id"];
  const type = getEntityType(entityData["@type"]);
  const label = entityData.name || entityData.label || entityData["@id"];
  const displayName = abbreviateName(label);
  const description = entityData.description || "";

  const relationships = dataService.getAllRelationships(id);
  const hasExpandableRelationships =
    relationships.generatedBy.length > 0 ||
    relationships.usedDataset.length > 0 ||
    relationships.usedSoftware.length > 0 ||
    relationships.usedSample.length > 0 ||
    relationships.usedInstrument.length > 0;

  const visibleRelatedNodes = [
    ...relationships.generatedBy,
    ...relationships.usedDataset,
    ...relationships.usedSoftware,
    ...relationships.usedSample,
    ...relationships.usedInstrument,
  ].filter((node) => visibleNodes.has(node["@id"]));

  const isExpandable =
    hasExpandableRelationships &&
    visibleRelatedNodes.length <
      [
        ...relationships.generatedBy,
        ...relationships.usedDataset,
        ...relationships.usedSoftware,
        ...relationships.usedSample,
        ...relationships.usedInstrument,
      ].length;

  const nodeData: EvidenceNodeData = {
    id,
    type,
    label,
    displayName,
    description,
    expandable: isExpandable,
    _sourceData: entityData,
    properties: getDisplayableProperties(entityData),
    _expanded: !isExpandable,
  };

  return {
    id,
    type: "evidenceNode",
    position: { x: 0, y: 0 },
    data: nodeData,
  };
}

export function createEdge(
  sourceId: string,
  targetId: string,
  relationshipType: string
): EvidenceEdge {
  const labelMap: { [key: string]: string } = {
    generatedBy: "generated by",
    usedDataset: "used dataset",
    usedSoftware: "used software",
    usedSample: "used sample",
    usedInstrument: "used instrument",
  };

  const label = labelMap[relationshipType] || relationshipType;
  const edgeId = `${sourceId}_${relationshipType}_${targetId}`;

  return {
    id: edgeId,
    source: sourceId,
    target: targetId,
    type: "smoothstep",
    label,
  };
}

export interface GraphElements {
  nodes: EvidenceNode[];
  edges: EvidenceEdge[];
}

export class GraphBuilder {
  private dataService: GraphDataService;
  private visibleNodes: Set<string>;
  private nodes: Map<string, EvidenceNode>;
  private edges: Map<string, EvidenceEdge>;

  constructor(dataService: GraphDataService) {
    this.dataService = dataService;
    this.visibleNodes = new Set();
    this.nodes = new Map();
    this.edges = new Map();
  }

  buildInitialGraph(depth: number = 2): GraphElements {
    const outputNodes = this.dataService.getOutputNodes();

    for (const outputNode of outputNodes) {
      this.addNodeAndRelationships(outputNode["@id"], depth);
    }

    return {
      nodes: Array.from(this.nodes.values()),
      edges: Array.from(this.edges.values()),
    };
  }

  buildPathGraph(path: string[]): GraphElements {
    for (let i = 0; i < path.length; i++) {
      const nodeId = path[i];
      this.addNode(nodeId);

      if (i > 0) {
        const prevNodeId = path[i - 1];
        const prevNode = this.dataService.getNode(prevNodeId);
        const currentNode = this.dataService.getNode(nodeId);

        if (prevNode && currentNode) {
          const relationshipType = this.findRelationshipType(
            prevNodeId,
            nodeId
          );
          if (relationshipType) {
            const edge = createEdge(prevNodeId, nodeId, relationshipType);
            this.edges.set(edge.id, edge);
          }
        }
      }
    }

    return {
      nodes: Array.from(this.nodes.values()),
      edges: Array.from(this.edges.values()),
    };
  }

  expandNode(nodeId: string): GraphElements {
    const nodeEntity = this.dataService.getNode(nodeId);
    if (!nodeEntity) return this.getElements();

    const relationships = this.dataService.getAllRelationships(nodeId);

    for (const relNode of relationships.generatedBy) {
      this.addNode(relNode["@id"]);
      const edge = createEdge(nodeId, relNode["@id"], "generatedBy");
      this.edges.set(edge.id, edge);
    }

    for (const relNode of relationships.usedDataset) {
      this.addNode(relNode["@id"]);
      const edge = createEdge(nodeId, relNode["@id"], "usedDataset");
      this.edges.set(edge.id, edge);
    }

    for (const relNode of relationships.usedSoftware) {
      this.addNode(relNode["@id"]);
      const edge = createEdge(nodeId, relNode["@id"], "usedSoftware");
      this.edges.set(edge.id, edge);
    }

    for (const relNode of relationships.usedSample) {
      this.addNode(relNode["@id"]);
      const edge = createEdge(nodeId, relNode["@id"], "usedSample");
      this.edges.set(edge.id, edge);
    }

    for (const relNode of relationships.usedInstrument) {
      this.addNode(relNode["@id"]);
      const edge = createEdge(nodeId, relNode["@id"], "usedInstrument");
      this.edges.set(edge.id, edge);
    }

    const node = this.nodes.get(nodeId);
    if (node) {
      node.data._expanded = true;
      node.data.expandable = false;
    }

    return this.getElements();
  }

  private addNode(nodeId: string): void {
    if (this.visibleNodes.has(nodeId)) return;

    const nodeEntity = this.dataService.getNode(nodeId);
    if (!nodeEntity) return;

    const node = createEvidenceNode(
      nodeEntity,
      this.visibleNodes,
      this.dataService
    );
    this.nodes.set(nodeId, node);
    this.visibleNodes.add(nodeId);
  }

  private addNodeAndRelationships(nodeId: string, depth: number): void {
    if (depth <= 0 || this.visibleNodes.has(nodeId)) return;

    this.addNode(nodeId);

    if (depth > 1) {
      const relationships = this.dataService.getAllRelationships(nodeId);

      for (const relNode of relationships.generatedBy) {
        this.addNodeAndRelationships(relNode["@id"], depth - 1);
        const edge = createEdge(nodeId, relNode["@id"], "generatedBy");
        this.edges.set(edge.id, edge);
      }

      for (const relNode of relationships.usedDataset) {
        this.addNodeAndRelationships(relNode["@id"], depth - 1);
        const edge = createEdge(nodeId, relNode["@id"], "usedDataset");
        this.edges.set(edge.id, edge);
      }

      for (const relNode of relationships.usedSoftware) {
        this.addNodeAndRelationships(relNode["@id"], depth - 1);
        const edge = createEdge(nodeId, relNode["@id"], "usedSoftware");
        this.edges.set(edge.id, edge);
      }

      for (const relNode of relationships.usedSample) {
        this.addNodeAndRelationships(relNode["@id"], depth - 1);
        const edge = createEdge(nodeId, relNode["@id"], "usedSample");
        this.edges.set(edge.id, edge);
      }

      for (const relNode of relationships.usedInstrument) {
        this.addNodeAndRelationships(relNode["@id"], depth - 1);
        const edge = createEdge(nodeId, relNode["@id"], "usedInstrument");
        this.edges.set(edge.id, edge);
      }
    }
  }

  private findRelationshipType(
    sourceId: string,
    targetId: string
  ): string | null {
    const sourceNode = this.dataService.getNode(sourceId);
    if (!sourceNode) return null;

    const relationships = [
      {
        type: "generatedBy",
        nodes: this.dataService.getRelatedNodes(sourceId, "generatedBy"),
      },
      {
        type: "usedDataset",
        nodes: this.dataService.getRelatedNodes(sourceId, "usedDataset"),
      },
      {
        type: "usedSoftware",
        nodes: this.dataService.getRelatedNodes(sourceId, "usedSoftware"),
      },
      {
        type: "usedSample",
        nodes: this.dataService.getRelatedNodes(sourceId, "usedSample"),
      },
      {
        type: "usedInstrument",
        nodes: this.dataService.getRelatedNodes(sourceId, "usedInstrument"),
      },
    ];

    for (const rel of relationships) {
      if (rel.nodes.some((node) => node["@id"] === targetId)) {
        return rel.type;
      }
    }

    return null;
  }

  getElements(): GraphElements {
    return {
      nodes: Array.from(this.nodes.values()),
      edges: Array.from(this.edges.values()),
    };
  }
}
