export interface MetadataProperty {
  key: string;
  name: string;
}

export const ROCrateProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier (ARK)" },
  { key: "name", name: "Name" },
  { key: "description", name: "Description" },
  { key: "keywords", name: "Keywords" },
  { key: "author", name: "Author(s)" },
  { key: "version", name: "Version" },
  { key: "license", name: "License" },
  { key: "contentSize", name: "Content Size" },
  { key: "datePublished", name: "Date Published" },
  { key: "contactEmail", name: "Contact Email" },
  { key: "associatedPublication", name: "Associated Publication" },
  { key: "hasPart", name: "Contains" },
  { key: "isPartOf", name: "Is Part Of" },
  { key: "funder", name: "Funding" },
];

export const DatasetProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier (ARK)" },
  { key: "name", name: "Name" },
  { key: "description", name: "Description" },
  { key: "author", name: "Author(s)" },
  { key: "datePublished", name: "Date Published" },
  { key: "version", name: "Version" },
  { key: "keywords", name: "Keywords" },
  { key: "format", name: "Format" },
  { key: "associatedPublication", name: "Associated Publication" },
  { key: "additionalDocumentation", name: "Documentation" },
  { key: "contentUrl", name: "Content URL" },
  { key: "generatedBy", name: "Generated By" },
  { key: "derivedFrom", name: "Derived From" },
  { key: "usedByComputation", name: "Used By" },
  { key: "EVI:schema", name: "Schema" },
];

export const SoftwareProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier (ARK)" },
  { key: "name", name: "Name" },
  { key: "description", name: "Description" },
  { key: "author", name: "Author(s)" },
  { key: "dateModified", name: "Last Modified" },
  { key: "version", name: "Version" },
  { key: "keywords", name: "Keywords" },
  { key: "format", name: "Format" },
  { key: "associatedPublication", name: "Associated Publication" },
  { key: "additionalDocumentation", name: "Documentation" },
  { key: "usedByComputation", name: "Used By" },
  { key: "contentUrl", name: "Download URL" },
];

export const ComputationProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier (ARK)" },
  { key: "name", name: "Name" },
  { key: "description", name: "Description" },
  { key: "runBy", name: "Run By" },
  { key: "dateCreated", name: "Date Created" },
  { key: "keywords", name: "Keywords" },
  { key: "associatedPublication", name: "Associated Publication" },
  { key: "additionalDocumentation", name: "Documentation" },
  { key: "command", name: "Command" },
  { key: "usedSoftware", name: "Used Software" },
  { key: "usedDataset", name: "Used Datasets" },
  { key: "generated", name: "Generated" },
];

export const SchemaProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier (ARK)" },
  { key: "name", name: "Schema Name" },
  { key: "description", name: "Description" },
  { key: "license", name: "License" },
  { key: "keywords", name: "Keywords" },
  { key: "published", name: "Published" },
  { key: "properties", name: "Properties" },
  { key: "type", name: "Schema Type" },
  { key: "additionalProperties", name: "Additional Properties" },
  { key: "required", name: "Required Fields" },
  { key: "separator", name: "Separator" },
  { key: "header", name: "Has Header" },
  { key: "examples", name: "Examples" },
];

export const GenericProperties: MetadataProperty[] = [
  { key: "@id", name: "Identifier" },
  { key: "name", name: "Name" },
  { key: "description", name: "Description" },
];
